using System.Text;
using KbdLayoutTool.Core.Models;

namespace KbdLayoutTool.Core.Services;

/// <summary>
/// Generates a Windows .reg file (UTF-16 LE with BOM, CRLF) that applies or clears
/// the override for one or more devices — so the change can be re-applied later,
/// deployed to another machine, or kept as a backup.
/// </summary>
public sealed class RegFileExporter
{
    public string BuildContent(IEnumerable<KeyboardDevice> devices, KeyboardLayoutPreset preset)
    {
        var sb = new StringBuilder();
        sb.Append("Windows Registry Editor Version 5.00\r\n\r\n");
        sb.Append($"; Generated by KbdLayoutTool — preset: {preset.DisplayName}\r\n");
        sb.Append("; Per-device HID value names: KeyboardTypeOverride / KeyboardSubtypeOverride.\r\n");
        sb.Append("; A reconnect (USB replug / BT reconnect) or reboot is required to take effect.\r\n\r\n");

        foreach (var d in devices)
        {
            sb.Append($"; {d.ProductName} [{d.BusLabel}] {d.CollectionTag}\r\n");
            sb.Append($"[HKEY_LOCAL_MACHINE\\{d.DeviceParametersSubKey}]\r\n");
            if (preset.IsClear)
            {
                sb.Append($"\"{OverrideService.TypeValueName}\"=-\r\n");
                sb.Append($"\"{OverrideService.SubtypeValueName}\"=-\r\n");
            }
            else
            {
                sb.Append($"\"{OverrideService.TypeValueName}\"=dword:{preset.Type!.Value:x8}\r\n");
                sb.Append($"\"{OverrideService.SubtypeValueName}\"=dword:{preset.Subtype!.Value:x8}\r\n");
            }
            sb.Append("\r\n");
        }

        return sb.ToString();
    }

    /// <summary>Writes the .reg file as UTF-16 LE with BOM (the encoding regedit expects).</summary>
    public void Write(string path, IEnumerable<KeyboardDevice> devices, KeyboardLayoutPreset preset)
    {
        var content = BuildContent(devices, preset);
        var encoding = new UnicodeEncoding(bigEndian: false, byteOrderMark: true);
        File.WriteAllText(path, content, encoding);
    }
}
